
---
Standards:
  -
    Title: About PSEs
    Description: About Weekly Problem-Solving Exercises 
    UID: 1e030b14-342a-49b5-89b5-4472f165cbfb
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: a6af8fa6bab71c8b803ecaf34e0984c1
        Path: 00-about-pses/01-about-pses.md
  -
    Title: PSE 1
    Description: Problem Solving Exercise 1
    UID: ef4fcb90-29f4-4f87-b2d7-6c61f61a3d50
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Checkpoint
        UID: 1caa645b-5306-4ba3-b37f-c02d11bb680e
        Path: /01-pse-01/01-wk02-pse-checkpoint.md
